server:
  PORT: {{ .port }}
db:
  mysql:
    USER_NAME: "root"
    PASSWORD: 123456
    URL: {{ .mysql_url }}
    PORT: {{ .mysql_port }}
    DB_NAME: "gin_chat"
    # 慢sql阈值，单位毫秒
    SlowThreshold: 100
    # 日志打印级别
    LogLevel: info
    # 是否彩色打印sql
    Colorful: true
  redis:
    URL: {{ .redis_url }}
    PORT: {{ .redis_port }}
    PASSWORD: ""
    DB: 0
    # 数据库连接池连接数量
    POOL_SIZE: 30
    # 
    MinIdleConns: 10
    # 超时时间，单位毫秒
    PoolTimeout: 30
  mongodb:
    USER_NAME: "root"
    PASSWORD: 123456
    URL: {{ .mongodb_url }}
    PORT: {{ .mongo_port }}
    DB_NAME: "gin_chat"

