definitions:
  models.UserBasic:
    type: object
info:
  contact: {}
  title: Swagger Example API
paths:
  /user/delOne:
    post:
      parameters:
      - description: 上传的JSON
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.UserBasic'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: UserBasic
      summary: 参数类型：{"userId":123456,"isLogicDel":true}
      tags:
      - 删除一个用户
  /user/login:
    post:
      parameters:
      - description: 上传的JSON
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.UserBasic'
      produces:
      - application/json
      responses: {}
      tags:
      - 通用登录接口
  /user/pageQuery:
    get:
      parameters:
      - default: 1
        description: 第几页
        in: query
        name: pageNo
        required: true
        type: integer
      - default: 10
        description: 每页多少条
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: UserBasic
      summary: 分页查询
      tags:
      - 用户相关
  /user/pageQueryByFilter:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: UserBasic
      summary: 前端请求参数应为：http://xx:xx/pageQueryByFilter?pageSize=1&pageNo=1&name=1&age=2&email=xxx@xxx
      tags:
      - 用户相关
  /user/register:
    post:
      parameters:
      - description: 上传的JSON
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.UserBasic'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: UserBasic
      summary: 用于用户注册
      tags:
      - 创建一个用户
  /user/update:
    post:
      parameters:
      - description: 上传的JSON
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models.UserBasic'
      produces:
      - application/json
      responses: {}
      tags:
      - 更新用户信息
swagger: "2.0"
